# app.py
from fastapi import FastAPI, HTTPException, Depends, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
from pydantic import BaseModel, constr, conint
from typing import List, Optional
from sqlalchemy.orm import Session
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import logging
import uvicorn
import os

# Database setup
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./test.db")
engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

# Logging setup
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# CORS setup
origins = ["*"]  # Adjust this in production
app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Security setup
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="token")

# Models
class SimulationRequest(BaseModel):
    urban_area: constr(min_length=1)
    climate_factor: constr(min_length=1)
    simulation_duration: conint(gt=0)

class SimulationResponse(BaseModel):
    id: int
    result: str
    status: str

# Dependency
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

# Custom exceptions
class SimulationError(Exception):
    def __init__(self, detail: str):
        self.detail = detail

@app.exception_handler(SimulationError)
async def simulation_error_handler(request: Request, exc: SimulationError):
    logger.error(f"Simulation error: {exc.detail}")
    return JSONResponse(
        status_code=422,
        content={"code": "simulation_error", "message": exc.detail},
    )

# API Endpoints
@app.post("/api/v1/simulations", response_model=SimulationResponse)
async def create_simulation(simulation_request: SimulationRequest, db: Session = Depends(get_db)):
    try:
        # Simulate processing logic
        result = f"Simulated impact for {simulation_request.urban_area} with climate factor {simulation_request.climate_factor}"
        simulation_id = 1  # This would be generated by the database in a real scenario
        return SimulationResponse(id=simulation_id, result=result, status="completed")
    except Exception as e:
        raise SimulationError(detail=str(e))

@app.get("/api/v1/simulations/{simulation_id}", response_model=SimulationResponse)
async def get_simulation(simulation_id: int, db: Session = Depends(get_db)):
    # Here you would fetch the simulation result from the database
    # For demonstration, we return a mock response
    return SimulationResponse(id=simulation_id, result="Mock result", status="completed")

@app.get("/health")
async def health_check():
    return {"status": "healthy"}

@app.get("/readiness")
async def readiness_check():
    return {"status": "ready"}

# Main entry point
if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)